parameters:
#    sf_vlc_main.example.class: SfVlc\MainBundle\Example

services:
#    sf_vlc_main.example:
#        class: %sf_vlc_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]